In [1]:
import numpy as np

#initialize an array with zeros
d = np.zeros(5)


In [2]:
#broadcasting

A = np.array([[5,6,9,8],
             [9,5,3,1],
             [63,63,35,52]])

print(A)

[[ 5  6  9  8]
 [ 9  5  3  1]
 [63 63 35 52]]


In [3]:
calories = A.sum(axis=0)
print(calories)

[77 74 47 61]


In [11]:
percentage = 100 * A/calories.reshape(1,4)
print(percentage)

[[ 6.49350649  8.10810811 19.14893617 13.1147541 ]
 [11.68831169  6.75675676  6.38297872  1.63934426]
 [81.81818182 85.13513514 74.46808511 85.24590164]]
